[workspace]
resolver = "2"
members = [
    "vmm",
    "cni",
    "microseg",
    "drs",
    "bts",
    "livemig",
    "gpu",
    "api",
    "cli",
    "mcp",
]

[workspace.package]
version     = "0.3.0"
edition     = "2021"
authors     = ["Caimán OS Contributors"]
license     = "Apache-2.0"
repository  = "https://github.com/teampmladv/caiman-os"
homepage    = "https://caiman.io"
description = "Caimán OS — KVM hypervisor without QEMU. Born in Cuba. Built for the cloud."

[workspace.dependencies]
tokio       = { version = "1", features = ["full"] }
futures     = "0.3"
async-trait = "0.1"
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"
anyhow      = "1"
thiserror   = "1"
tracing     = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid   = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }

[profile.release]
opt-level    = 3
lto          = "thin"
codegen-units= 1
strip        = "symbols"
panic        = "abort"

[profile.dev]
opt-level = 0
debug     = true
