[package]
name        = "caiman"
version     = "1.0.0"
edition     = "2021"
description = "Caimán OS CLI — manage VMs, DRS, storage and GPU"
license     = "Apache-2.0"

[[bin]]
name = "caiman"
path = "src/main.rs"

[dependencies]
clap         = { version = "4", features = ["derive", "env", "color", "wrap_help"] }
tokio        = { version = "1", features = ["full"] }
reqwest      = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
futures      = "0.3"
comfy-table  = { version = "7", features = ["tty"] }
colored      = "2"
serde_json   = "1"
serde_yaml   = "0.9"
serde        = { version = "1", features = ["derive"] }
config       = "0.14"
dirs         = "5"
anyhow       = "1"
thiserror    = "1"
tracing      = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono       = { version = "0.4", features = ["serde"] }
humantime    = "2"
uuid         = { version = "1", features = ["v4"] }
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-native-roots"] }
toml = "0.8"
