name: Bug report
description: Reportar un bug en Caimán OS
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: subsystem
    attributes:
      label: Subsistema afectado
      options: [vmm, kernel/XDP, microseg, drs, storage, livemig, gpu, bts, ui, cli, install]
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Descripción del problema
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Pasos para reproducir
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
  - type: input
    id: version
    attributes:
      label: Versión de Caimán OS
      placeholder: v0.1.0
