[package]
name        = "caiman-vmm"
version     = "1.2.0"
edition     = "2021"
description = "Caimán OS — KVM VMM without QEMU"
license     = "Apache-2.0"

[[bin]]
name = "caiman-vmm"
path = "src/main.rs"

[dependencies]
kvm-ioctls   = "0.17"
kvm-bindings = { version = "0.8", features = ["fam-wrappers"] }
libc         = "0.2"
vmm-sys-util = "0.12"   # EventFd, only

clap  = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

anyhow  = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
