[package]
name        = "caiman-api"
version     = "1.0.3"
edition     = "2021"
description = "Caimán OS — REST API + WebSocket"
license     = "Apache-2.0"

[[bin]]
name = "caiman-api"
path = "src/main.rs"

[dependencies]
tokio        = { version = "1", features = ["full"] }
axum         = { version = "0.7", features = ["ws", "macros"] }
tower-http   = { version = "0.5", features = ["cors"] }
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
anyhow       = "1"
tracing      = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid         = { version = "1", features = ["v4"] }
chrono       = { version = "0.4", features = ["serde"] }
sysinfo      = "0.30"
tokio-stream = "0.1"
futures      = "0.3"
libc = "0.2"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
rand = "0.8"
